# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /vscmnt/brussel_pixiu_apps/_apps_brussel/RL9/zen5-ib/software/CMake/3.29.3-GCCcore-13.3.0/bin/cmake

# The command to remove a file.
RM = /vscmnt/brussel_pixiu_apps/_apps_brussel/RL9/zen5-ib/software/CMake/3.29.3-GCCcore-13.3.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/vscmnt/brussel_pixiu_apps/_apps_brussel/RL9/broadwell/software/CMake/3.29.3-GCCcore-13.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/vscmnt/brussel_pixiu_apps/_apps_brussel/RL9/zen5-ib/software/CMake/3.29.3-GCCcore-13.3.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build/CMakeFiles /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlashElectronSim

# Build rule for target.
FlashElectronSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlashElectronSim
.PHONY : FlashElectronSim

# fast build rule for target.
FlashElectronSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/build
.PHONY : FlashElectronSim/fast

src/ActionInitialization.o: src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/Analysis.o: src/Analysis.cc.o
.PHONY : src/Analysis.o

# target to build an object file
src/Analysis.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/Analysis.cc.o
.PHONY : src/Analysis.cc.o

src/Analysis.i: src/Analysis.cc.i
.PHONY : src/Analysis.i

# target to preprocess a source file
src/Analysis.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/Analysis.cc.i
.PHONY : src/Analysis.cc.i

src/Analysis.s: src/Analysis.cc.s
.PHONY : src/Analysis.s

# target to generate assembly for a file
src/Analysis.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/Analysis.cc.s
.PHONY : src/Analysis.cc.s

src/BeamlineGeometry.o: src/BeamlineGeometry.cc.o
.PHONY : src/BeamlineGeometry.o

# target to build an object file
src/BeamlineGeometry.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/BeamlineGeometry.cc.o
.PHONY : src/BeamlineGeometry.cc.o

src/BeamlineGeometry.i: src/BeamlineGeometry.cc.i
.PHONY : src/BeamlineGeometry.i

# target to preprocess a source file
src/BeamlineGeometry.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/BeamlineGeometry.cc.i
.PHONY : src/BeamlineGeometry.cc.i

src/BeamlineGeometry.s: src/BeamlineGeometry.cc.s
.PHONY : src/BeamlineGeometry.s

# target to generate assembly for a file
src/BeamlineGeometry.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/BeamlineGeometry.cc.s
.PHONY : src/BeamlineGeometry.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/ExitPlane.o: src/ExitPlane.cc.o
.PHONY : src/ExitPlane.o

# target to build an object file
src/ExitPlane.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ExitPlane.cc.o
.PHONY : src/ExitPlane.cc.o

src/ExitPlane.i: src/ExitPlane.cc.i
.PHONY : src/ExitPlane.i

# target to preprocess a source file
src/ExitPlane.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ExitPlane.cc.i
.PHONY : src/ExitPlane.cc.i

src/ExitPlane.s: src/ExitPlane.cc.s
.PHONY : src/ExitPlane.s

# target to generate assembly for a file
src/ExitPlane.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/ExitPlane.cc.s
.PHONY : src/ExitPlane.cc.s

src/PhantomGeometry.o: src/PhantomGeometry.cc.o
.PHONY : src/PhantomGeometry.o

# target to build an object file
src/PhantomGeometry.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PhantomGeometry.cc.o
.PHONY : src/PhantomGeometry.cc.o

src/PhantomGeometry.i: src/PhantomGeometry.cc.i
.PHONY : src/PhantomGeometry.i

# target to preprocess a source file
src/PhantomGeometry.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PhantomGeometry.cc.i
.PHONY : src/PhantomGeometry.cc.i

src/PhantomGeometry.s: src/PhantomGeometry.cc.s
.PHONY : src/PhantomGeometry.s

# target to generate assembly for a file
src/PhantomGeometry.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PhantomGeometry.cc.s
.PHONY : src/PhantomGeometry.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o
.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i
.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s
.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o
.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i
.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s
.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashElectronSim.dir/build.make CMakeFiles/FlashElectronSim.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FlashElectronSim"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/Analysis.o"
	@echo "... src/Analysis.i"
	@echo "... src/Analysis.s"
	@echo "... src/BeamlineGeometry.o"
	@echo "... src/BeamlineGeometry.i"
	@echo "... src/BeamlineGeometry.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/ExitPlane.o"
	@echo "... src/ExitPlane.i"
	@echo "... src/ExitPlane.s"
	@echo "... src/PhantomGeometry.o"
	@echo "... src/PhantomGeometry.i"
	@echo "... src/PhantomGeometry.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /scratch/brussel/113/vsc11383/projects/third_sim/FlashElectronSim/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

